spring.application.name=payment-service
spring.profiles.active=local

server.port=${SERVER_PORT:8083}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=${KAFKA_SERVERS}

kafka.topics.order-created=${KAFKA_TOPIC_ORDER_CREATED}
kafka.topics.payment-completed=${KAFKA_TOPIC_PAYMENT_COMPLETED}
kafka.topics.payment-failed=${KAFKA_TOPIC_PAYMENT_FAILED}
kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true