spring.application.name=order-service
server.port=8082

# Datasource ? misma BD que product o una propia
spring.datasource.url=jdbc:mysql://localhost:3306/bd_ecommerce
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Url microservice product-service
services.product.url=http://localhost:0909

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Topics ? los @Value de KafkaConfig y OrderKafkaPublisher
kafka.topics.order-created=order.created
kafka.topics.order-cancelled=order.cancelled
