#Variables de Entorno

spring.application.name=order-service
spring.profiles.active=local

server.port=${SERVER_PORT:8082}

# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Url microservice product-service
services.product.url=${PRODUCT_SERVICE_URL}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}

# Kafka Topics
kafka.topics.order-created=${KAFKA_TOPIC_ORDER_CREATED}
kafka.topics.order-status-changed=${KAFKA_TOPIC_ORDER_STATUS_CHANGED}
kafka.topics.payment-completed=${KAFKA_TOPIC_PAYMENT_COMPLETED}
kafka.topics.payment-failed=${KAFKA_TOPIC_PAYMENT_FAILED}

# Consumer
kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true